name: Release

on:
  push:
    tags:
      - 'v*'  # Run when a tag starting with 'v' is pushed

# Disable notifications
env:
  GITHUB_ACTIONS_SKIP_NOTIFICATIONS: true
  ACTIONS_STEP_DEBUG: false
  GITHUB_ACTIONS_NOTIFICATIONS: false

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.os == 'windows-latest' && 'x64' || 'x86_64' }}
          args: --release --strip
          sccache: 'true'
          python-version: ${{ matrix.python-version }}
          
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: target/wheels/*.whl

  # Special job for building manylinux wheels
  build_manylinux:
    name: Build manylinux wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Build manylinux wheels
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          args: --release --strip --compatibility manylinux2014
          sccache: 'true'
          manylinux: '2014'
          python-version: '3.10 3.11'
          
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-manylinux
          path: target/wheels/*.whl

  publish:
    name: Create GitHub Release
    needs: [build_wheels, build_manylinux]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: wheels
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: wheels/**/*.whl
          draft: false
          prerelease: false
          generate_release_notes: true 